import type { Metadata } from "next";
<<<<<<< HEAD
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";

const font = Poppins({ subsets: ["latin"] ,weight:'300'});

//static metadata
export const metadata: Metadata = {
  title: "Belle",
  description: "Life is what you make of it so make it beautiful",
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 72d85aa (Initial commit from Create Next App)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={font.className}>
          <Header />
          <div className="mt-16">
            {children}
          </div>
          <Footer />
=======
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
>>>>>>> 72d85aa (Initial commit from Create Next App)
      </body>
    </html>
  );
}
